### ISSUE TITLE
Add a way to specify number of simulations

### ISSUE THREAD

**Issue by TechnologyClassroom** [TechnologyClassroom/dice-mechanic-sim#11]
In `builddatapack.sh`, the simulation is run 40 times.  Add an optional argument to change that value.  If you are familiar with bash, this is really easy.

**Comment by vmtenorio** [comment]
Could you please assign this one to me?

**Comment by TechnologyClassroom** [comment]
@vmtenorio Welcome! I assigned this issue to you. Let me know if you need help.

**Comment by vmtenorio** [comment]
Please let me know if you wanted something different! Happy to contribute!
