### ISSUE TITLE
Run black on all python files in this repository

### ISSUE THREAD

**Issue by TechnologyClassroom** [TechnologyClassroom/dice-mechanic-sim#14]
[black](https://github.com/psf/black) is a program that formats code into the [PEP 8 style guide](https://www.python.org/dev/peps/pep-0008/).

By default, `black` uses 88 characters as the default.  Override this to 79 characters with the additional argument `-l 79` so that the command would look like this: `black -l 79 dicemechanicsim.py`

Simply fork and clone this repo, install `black`, run `black` with the argument `-l 79` in addition to the filename to make the changes, commit those to a branch, and make a pull request of those changes.

**Comment by neil007m** [comment]
On it, feel free to assign it to me.
