### ISSUE TITLE
Add license headers

### ISSUE THREAD

**Issue by TechnologyClassroom** [TechnologyClassroom/dice-mechanic-sim#15]
Add the license header information according to the instructions in the last section `How to Apply These Terms to Your New Programs` of the license: <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by maria-ilie** [comment]
Hi @TechnologyClassroom, does this need to be added to all the .py files in the project?

**Comment by TechnologyClassroom** [comment]
@maria-ilie Welcome!  Yes, and also all of the `.sh` files in the project.

The copyright line would look like this:

```
# Copyright (C) 2017-2020 Michael McMahon
```
