### ISSUE TITLE
Change variable H to S

### ISSUE THREAD

**Issue by TechnologyClassroom** [TechnologyClassroom/dice-mechanic-sim#3]
Replace variable `H` with `S` in `dicemechanicsim.py`.  `H` stood for happening, but it should really be `S` for scene.  Yes, it really is that simple.

**Comment by ozancaglar** [comment]
Please assign this to me, I know it's my first issue but I'm confident I can do it :)

**Comment by TechnologyClassroom** [comment]
@ozancaglar Welcome!  I assigned this issue to you.  This is the perfect first issue.  Let me know if you need help.
